force-app/main/default/objects/Centro_Estetico__c/Centro_Estetico__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para registrar y administrar detalles específicos relacionados con los centros estéticos que ofrecen servicios de medicina estética</description>
    <label>Centro Estético</label>
    <nameField>
        <label>Nombre del Centro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centros Estéticos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disponibilidad_Medica__c/Disponibilidad_Medica__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para registrar y gestionar los horarios y fechas específicas en las que un médico está disponible en un centro estético particular.</description>
    <label>Disponibilidad Médica</label>
    <nameField>
        <label>Fecha y Hora y Medico</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Disponibilidades Médicas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disponibilidad_Medica__c/fields/Centro_Estetico_Asociado__c.field-meta.xml
<CustomField>
    <fullName>Centro_Estetico_Asociado__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Centro estético donde el médico está disponible</description>
    <label>Centro Estético Asociado</label>
    <referenceTo>Centro_Estetico__c</referenceTo>
    <relationshipLabel>Disponibilidades Médicas</relationshipLabel>
    <relationshipName>Disponibilidades_Medicas</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Disponibilidad_Medica__c/fields/Fecha_hora_de_Fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_hora_de_Fin__c</fullName>
    <label>Fecha/hora de Fin</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Disponibilidad_Medica__c/fields/Fecha_hora_de_Inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_hora_de_Inicio__c</fullName>
    <description>Hora de inicio de la disponibilidad del médico</description>
    <label>Fecha/hora de Inicio</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Disponibilidad_Medica__c/fields/Medico_Asociado__c.field-meta.xml
<CustomField>
    <fullName>Medico_Asociado__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Médico al cual pertenece esta disponibilidad.</description>
    <label>Médico Asociado</label>
    <referenceTo>Medico__c</referenceTo>
    <relationshipLabel>Disponibilidades Médicas</relationshipLabel>
    <relationshipName>Disponibilidades_Medicas</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Medico__c/Medico__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para registrar y administrar detalles específicos relacionados con médicos que trabajan en los centros estéticos</description>
    <label>Médico</label>
    <nameField>
        <label>Nombre del Médico</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Médicos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CreateAvailabilityLWCController.cls
/**
 * @description       : 
 * @author            : Adrian Romero
 * @group             : 
 * @last modified on  : 08-23-2023
 * @last modified by  : Adrian Romero
**/
public with sharing class CreateAvailabilityLWCController {

    @AuraEnabled(cacheable=true)
    public static List<Medico__c> getDoctors(String searchTerm) {
        // Si el término de búsqueda tiene menos de 3 caracteres, retornar una lista vacía
        if (searchTerm == null || searchTerm.length() < 3) {
            return new List<Medico__c>();
        }

        String query = 'SELECT Id, Name FROM Medico__c WHERE Name LIKE :searchTerm ORDER BY Name LIMIT 5';
        searchTerm = '%' + searchTerm + '%'; // Agregar comodines para la búsqueda parcial

        return Database.query(query);
    }

    @AuraEnabled(cacheable=true)
    public static List<Centro_Estetico__c> getCenters() {
        return [SELECT Id, Name FROM Centro_Estetico__c ORDER BY Name];
    }


    @AuraEnabled
    public static void createAvailabilities(String selectedCenter, String selectedCenterName, String startDate, String endDate, String selectedStartHour, String selectedEndHour, List<Id> selectedDoctorIds) {
        // Convertir las fechas de inicio y fin en objetos de fecha
        Date startDateObj = Date.valueOf(startDate);
        Date endDateObj = Date.valueOf(endDate);

            // Convertir las horas de inicio y fin en objetos Time
            Integer startHour = Integer.valueOf(selectedStartHour.split(':')[0]);
            Integer endHour = Integer.valueOf(selectedEndHour.split(':')[0]);
            Time startTime = Time.newInstance(startHour, 0, 0, 0);
            Time endTime = Time.newInstance(endHour, 0, 0, 0);

        // Crear una lista de objetos que representan las disponibilidades a crear
        List<Disponibilidad_Medica__c> availabilities = new List<Disponibilidad_Medica__c>();
        
        // Recorrer cada médico seleccionado
        for (Id doctorId : selectedDoctorIds) {
            // Recorrer cada franja de fechas seleccionada
            Date currentDate = startDateObj;
            while (currentDate <= endDateObj) {
                // Obtener el nombre del médico (puede ser optimizado con una consulta previa)
                Medico__c doctor = [SELECT Name FROM Medico__c WHERE Id = :doctorId LIMIT 1];

                // Crear un objeto que representa la disponibilidad
                Disponibilidad_Medica__c availability = new Disponibilidad_Medica__c(
                    Name = doctor.Name + ' + ' + selectedCenterName + ' + ' + currentDate,
                    Centro_Estetico_Asociado__c = selectedCenter,
                    Medico_Asociado__c = doctorId,
                    Fecha_hora_de_Inicio__c = DateTime.newInstance(currentDate, startTime),
                    Fecha_hora_de_Fin__c = DateTime.newInstance(currentDate, endTime)
            
                );
                availabilities.add(availability);

                // Avanzar al siguiente día
                currentDate = currentDate.addDays(1);
            }
        }

        // Insertar los registros
        insert availabilities;
    }
}