force-app/main/default/objects/Centro_Estetico__c/Centro_Estetico__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para registrar y administrar detalles específicos relacionados con los centros estéticos que ofrecen servicios de medicina estética</description>
    <label>Centro Estético</label>
    <nameField>
        <label>Nombre del Centro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centros Estéticos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disponibilidad_Medica__c/Disponibilidad_Medica__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para registrar y gestionar los horarios y fechas específicas en las que un médico está disponible en un centro estético particular.</description>
    <label>Disponibilidad Médica</label>
    <nameField>
        <label>Fecha y Hora y Medico</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Disponibilidades Médicas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disponibilidad_Medica__c/fields/Centro_Estetico_Asociado__c.field-meta.xml
<CustomField>
    <fullName>Centro_Estetico_Asociado__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Centro estético donde el médico está disponible</description>
    <label>Centro Estético Asociado</label>
    <referenceTo>Centro_Estetico__c</referenceTo>
    <relationshipLabel>Disponibilidades Médicas</relationshipLabel>
    <relationshipName>Disponibilidades_Medicas</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Disponibilidad_Medica__c/fields/Fecha_hora_de_Fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_hora_de_Fin__c</fullName>
    <label>Fecha/hora de Fin</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Disponibilidad_Medica__c/fields/Fecha_hora_de_Inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_hora_de_Inicio__c</fullName>
    <description>Hora de inicio de la disponibilidad del médico</description>
    <label>Fecha/hora de Inicio</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Disponibilidad_Medica__c/fields/Medico_Asociado__c.field-meta.xml
<CustomField>
    <fullName>Medico_Asociado__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Médico al cual pertenece esta disponibilidad.</description>
    <label>Médico Asociado</label>
    <referenceTo>Medico__c</referenceTo>
    <relationshipLabel>Disponibilidades Médicas</relationshipLabel>
    <relationshipName>Disponibilidades_Medicas</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Medico__c/Medico__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para registrar y administrar detalles específicos relacionados con médicos que trabajan en los centros estéticos</description>
    <label>Médico</label>
    <nameField>
        <label>Nombre del Médico</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Médicos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestDisponibilidadMedicaTriggerHandler.cls
/**
 * @description       : 
 * @author            : Adrian Romero
 * @group             : 
 * @last modified on  : 08-23-2023
 * @last modified by  : Adrian Romero
**/
@isTest
private class TestDisponibilidadMedicaTriggerHandler {
    @isTest static void testHandleBeforeInsert() {
        // Preparar datos de prueba
        Centro_Estetico__c centro = new Centro_Estetico__c();
        insert centro;

        Medico__c medico = new Medico__c();
        insert medico;

        DateTime inicio = DateTime.newInstance(2023, 8, 26, 8, 0, 54);
        DateTime fin = DateTime.newInstance(2023, 8, 26, 15, 0, 54);

        Disponibilidad_Medica__c disponibilidad = new Disponibilidad_Medica__c(
            Medico_Asociado__c = medico.Id,
            Centro_Estetico_Asociado__c = centro.Id,
            Fecha_hora_de_Inicio__c = inicio,
            Fecha_hora_de_Fin__c = fin
        );
        insert disponibilidad;

        // Intentar insertar una disponibilidad duplicada
        Disponibilidad_Medica__c disponibilidadDuplicada = new Disponibilidad_Medica__c(
            Medico_Asociado__c = medico.Id,
            Centro_Estetico_Asociado__c = centro.Id,
            Fecha_hora_de_Inicio__c = inicio,
            Fecha_hora_de_Fin__c = fin
        );
        List<Disponibilidad_Medica__c> newAvailabilities = new List<Disponibilidad_Medica__c>{disponibilidadDuplicada};

        Test.startTest();
        // Llamar al método handleBeforeInsert
        DisponibilidadMedicaTriggerHandler.handleBeforeInsert(newAvailabilities);
        Test.stopTest();

        // Aserción para verificar que no se haya creado una disponibilidad duplicada
        List<Disponibilidad_Medica__c> disponibilidadesDelMedico = [SELECT Id FROM Disponibilidad_Medica__c WHERE Medico_Asociado__c = :medico.Id];
        System.assertEquals(1, disponibilidadesDelMedico.size(), 'No debería haber disponibilidades duplicadas para el mismo médico.');
    }
}